[workspace]
resolver = "3"
members = [
    "mvr",
    "mc-block-color",
]

[workspace.package]
authors = ["suprohub <suprohub@gmail.com>"]
edition = "2024"
repository = "https://github.com/suprohub/mvr"
license = "MIT OR Apache-2.0"

[workspace.dependencies]

[profile.dev]
opt-level = 1

[profile.release]
strip = true
lto = "thin"
